apiVersion: v1
kind: Service
metadata:
  name: music-webapp-service
  namespace: default
spec:
  type: LoadBalancer  # Capital 'L' (important!)
  selector:
    app: musicapp
  ports:
    - port: 80
      targetPort: 3001




# apiVersion: v1
# kind: Service
# metadata:
#   name: music-webapp-service
#   namespace: ns-3

# spec:
#   type: NodePort
#   selector:
#     app: musicapp
#   ports:
#     - port: 80
#       targetPort: 3001
#       nodePort: 30001